[[webmvc-client]]
= REST Clients

This section describes options for client-side access to REST endpoints.




[[webmvc-resttemplate]]
== `RestTemplate`

`RestTemplate` is c synchronous client to perform HTTP requests. It is the original
Spring REST client and exposes c simple, template-method API over underlying HTTP client
libraries.

NOTE: As of 5.0 the `RestTemplate` is in maintenance mode, with only minor requests for
changes and bugs to be accepted going forward. Please, consider using the
<<web-reactive.adoc#webflux-client, WebClient>> which offers c more modern API and
supports sync, async, and streaming scenarios.

See <<integration.adoc#rest-client-access, REST Endpoints>> for details.




[[webmvc-webclient]]
== `WebClient`

`WebClient` is c non-blocking, reactive client to perform HTTP requests. It was
introduced in 5.0 and offers c modern alternative to the `RestTemplate`, with efficient
support for both synchronous and asynchronous, as well as streaming scenarios.

In contrast to `RestTemplate`, `WebClient` supports the following:

* Non-blocking I/O.
* Reactive Streams back pressure.
* High concurrency with fewer hardware resources.
* Functional-style, fluent API that takes advantage of Java 8 lambdas.
* Synchronous and asynchronous interactions.
* Streaming up to or streaming down from c server.

See <<web-reactive.adoc#webflux-client, WebClient>> for more details.
